---
title: "Constructing hierarchies - tourism"
author: "Bohan Zhang"
date: "2023-10-27"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(cluster)
library(ggplot2)
source("R/representator.R")
path <- "tourism"
bfmethod <- "ets"
dt <- readRDS(sprintf("%s/%s/eval.rds", path, bfmethod))
dt_orig <- readRDS(sprintf("%s/%s/batch_0.rds", path, bfmethod))
dt_names <- readRDS(sprintf("%s/names.rds", path))
source("R/run_nls.R")
```

# Number of cluters of Kmedoids 

```{r number-of-cluster}
Kmedoids_clusterN(dt)
```

```{r number-of-cluster-dimension-reduction}
Kmedoids_clusterN(dt, cluster = "Kmedoids-dr")
```

```{r number-of-clusters-dimension-reduction-gap}
Kmedoids_gap(dt)
```

```{r number-of-clusters-dimension-reduction-gap-summary}
gap <- Kmedoids_gap(dt)
gap %>% group_by(representor, n_gap) %>% count()
gap %>% group_by(representor, n_gap, n_cluster) %>% count()
```



```{r visualize-distance-matrix-ts-euclidean}
visualizeDistance(dt_orig, "ts-dr", "euclidean", "Kmedoids-dr")
```

```{r inspect-silhouette}
inspect_silhouette(dt_orig, "ts-dr")
```

```{r visualize-distance-matrix-error}
visualizeDistance(dt_orig, "error-dr", "euclidean", "Kmedoids-dr")
```

```{r inspect-silhouette-error}
inspect_silhouette(dt_orig, "error-dr")
```


```{r visualize-distance-matrix-accuracy-euclidean}
visualizeDistance(dt_orig, "accuracy", "euclidean")
```

# Group Visualize

```{r visualize-group-results-error-dimension-reduction}
visualizeGroup(dt_orig, "error-dr", "euclidean", cluster= "Kmedoids-dr",names = dt_names)
```

```{r visualize-group-results-ts-dimension-reduction}
visualizeGroup(dt_orig, "ts-dr", "euclidean", cluster= "Kmedoids-dr",names = dt_names)
```
```{r visualize-group-results-tsfeatures-dimension-reduction}
visualizeGroup(dt_orig, "ts.features-dr", "euclidean", cluster= "Kmedoids-dr",names = dt_names)
```

```{r visualize-group-results-errorfeatures-dimension-reduction}
visualizeGroup(dt_orig, "error.features-dr", "euclidean", cluster= "Kmedoids-dr",names = dt_names)
```


# Overall statistics

```{r average-metric}
avg_measure_fn(dt, metric = "rmsse") %>% arrange(bottom)
```

# Overall rank mcb test

```{r compare-overall-rank}
rank_compare(dt, filter_random = TRUE)
```



