---
title: "Constructing hierarchies - mortality"
author: "Bohan Zhang"
date: "2023-10-22"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
source("R/representator.R")
path <- "mortality"
bfmethod <- "ets"
dt <- readRDS(sprintf("%s/%s/eval.rds", path, bfmethod))
dt_orig <- readRDS(sprintf("%s/%s/batch_120.rds", path, bfmethod))
dt_names <- readRDS(sprintf("%s/names.rds", path))
source("R/run_nls.R")
```

# Number of cluters of Kmedoids 

```{r number-of-cluster}
Kmedoids_clusterN(dt)
```

The below figure visualizes a euclidean distance matrix of time series.

```{r visualize-distance-matrix-ts-euclidean}
visualizeDistance(dt_orig, "ts", "euclidean")
```

```{r visualize-distance-matrix-error-dtw}
visualizeDistance(dt_orig, "error", "dtw")
```

```{r visualize-distance-matrix-forecast-euclidean}
visualizeDistance(dt_orig, "forecast", "euclidean")
```

```{r visualize-distance-matrix-accuracy-euclidean}
visualizeDistance(dt_orig, "accuracy", "euclidean")
```
# Group Visualize

```{r visualize-group-results-accuracy-euclidean}
visualizeGroup(dt_orig, "accuracy", "euclidean", names = dt_names)
```

```{r visualize-group-results-forecast-euclidean}
visualizeGroup(dt_orig, "forecast", "euclidean", names = dt_names)
```


# why there is no group when cluster by time series and error?

```{r include=FALSE}
library(cluster)
```

```{r pam-time-series-euclidean}
summary(silhouette(pam(dt_orig$distance$ts$euclidean, diss=TRUE, k=2)))
```
```{r gap-statistics-time-series}
clusGap(t(representator.ts(dt_orig)), pam, K.max = 20)
```

```{r pam-error-euclidean}
summary(silhouette(pam(dt_orig$distance$error$euclidean, diss=TRUE, k=2)))
```


# Overall statistics

```{r average-metric}
avg_measure_fn(dt, metric = "rmsse") %>% arrange(total)
```

# Overall rank mcb test

```{r compare-overall-rank}
rank_compare(dt)
```



